{
  "comments": [
    {
      "key": {
        "uuid": "AAAKzn////w\u003d",
        "filename": "subcmds/sync.py",
        "patchSetId": 2
      },
      "lineNbr": 333,
      "author": {
        "id": 1011123
      },
      "writtenOn": "2012-10-25T01:06:18Z",
      "side": 1,
      "message": "Won\u0027t this cause the thread to exit with an uncaught exception?",
      "revId": "5228e73fdf4221b7c1ff21ba3b34a23c42ab7fce",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "AAAKz3////w\u003d",
        "filename": "subcmds/sync.py",
        "patchSetId": 2
      },
      "lineNbr": 333,
      "author": {
        "id": 1010008
      },
      "writtenOn": "2012-10-25T01:08:08Z",
      "side": 1,
      "message": "Yes, I was just following the pattern in _FetchHelper.",
      "parentUuid": "AAAKzn////w\u003d",
      "revId": "5228e73fdf4221b7c1ff21ba3b34a23c42ab7fce",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}