{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "e3b1c2ea_33cbf566",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1011842
      },
      "writtenOn": "2021-02-18T20:32:16Z",
      "side": 1,
      "message": "Nice.",
      "revId": "b1f50894a39d73dd5d113cceaad6d9ad6f25b875",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "46bd9b96_b81fce72",
        "filename": "subcmds/init.py",
        "patchSetId": 1
      },
      "lineNbr": 203,
      "author": {
        "id": 1011842
      },
      "writtenOn": "2021-02-18T20:32:16Z",
      "side": 1,
      "message": "Should this error message change as well?",
      "revId": "b1f50894a39d73dd5d113cceaad6d9ad6f25b875",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}