{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "899f4154_7a684c37",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1023872
      },
      "writtenOn": "2023-08-25T19:54:15Z",
      "side": 1,
      "message": "was the previous change just an accident? (is it possible to add test coverage for this case to avoid future regressions?)",
      "revId": "bf0806d23515d703ebd24a43353ce9a750846a3b",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3ecb3d6e_073349ef",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1159376
      },
      "writtenOn": "2023-08-28T03:23:39Z",
      "side": 1,
      "message": "This one is tricky since it would involve execution of GitCommand which passes opens a subprocess. Introduction of the regression was a developer issue not understanding the side effects of capture_stderr",
      "parentUuid": "899f4154_7a684c37",
      "revId": "bf0806d23515d703ebd24a43353ce9a750846a3b",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8143c676_23c96066",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1023872
      },
      "writtenOn": "2023-08-28T13:34:49Z",
      "side": 1,
      "message": "My only concern is how we can avoid this sort of oops situation again. I am fine calling adding tests to this area as out of scope for this defect fix, but still something we should think about hardening.",
      "parentUuid": "3ecb3d6e_073349ef",
      "revId": "bf0806d23515d703ebd24a43353ce9a750846a3b",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}